# Generated by Django 3.0.5 on 2020-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('icon_url', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('0', 'male'), ('1', 'female')], default='female', max_length=6, verbose_name='gender')),
                ('personal_des', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='year-month-day')),
                ('mentoring_fields', models.TextField(default='non')),
                ('seeking_fields', models.TextField(default='non')),
                ('isAvailable', models.BooleanField(default=False)),
                ('language', models.CharField(default='english', max_length=100)),
                ('university', models.CharField(default='non', max_length=50)),
                ('degree', models.CharField(default='non', max_length=50)),
                ('country', models.CharField(default='non', max_length=50)),
                ('city', models.CharField(default='non', max_length=50)),
                ('current_business_title', models.TextField(default='non')),
                ('industry', models.CharField(default='non', max_length=50)),
                ('working_experience', models.TextField(default='non')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profile',
                'ordering': ['created'],
            },
        ),
    ]
