# Generated by Django 3.0.5 on 2020-05-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='non-fn', max_length=50)),
                ('last_name', models.CharField(blank=True, default='non-ln', max_length=50)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('okta_id', models.CharField(default='0', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('icon_url', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('0', 'male'), ('1', 'female')], default='female', max_length=6, verbose_name='gender')),
                ('personal_des', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='year-month-day')),
                ('mentoring_fields', models.TextField(default='non')),
                ('seeking_fields', models.TextField(default='non')),
                ('isAvailable', models.BooleanField(default=False)),
                ('language', models.CharField(default='english', max_length=100)),
                ('university', models.CharField(default='non', max_length=50)),
                ('degree', models.CharField(default='non', max_length=50)),
                ('country', models.CharField(default='non', max_length=50)),
                ('city', models.CharField(default='non', max_length=50)),
                ('current_business_title', models.TextField(default='non')),
                ('industry', models.CharField(default='non', max_length=50)),
                ('working_experience', models.TextField(default='non')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profile',
                'ordering': ['created'],
            },
        ),
    ]
