# Generated by Django 3.0.5 on 2020-05-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200430_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='user'),
        ),
    ]
