# Generated by Django 3.0.5 on 2020-05-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_advisor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='mentoringFields',
            new_name='mentoring_fields',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='seekingFields',
            new_name='seeking_fields',
        ),
    ]
