# Generated by Django 3.0.1 on 2020-04-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200411_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'seeker information', 'verbose_name_plural': 'seeker information'},
        ),
        migrations.AlterModelOptions(
            name='seeker',
            options={'verbose_name': 'seeker information', 'verbose_name_plural': 'seeker information'},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='language',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='language',
        ),
        migrations.AddField(
            model_name='mentor',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='year-month-day'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='year-month-day'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(choices=[('0', 'male'), ('1', 'female')], default='female', max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='gender',
            field=models.CharField(choices=[('0', 'male'), ('1', 'female')], default='female', max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='seekingFields',
            field=models.TextField(blank=True),
        ),
    ]
