# Generated by Django 3.0.5 on 2020-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200411_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'mentor information', 'verbose_name_plural': 'mentor information'},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='name',
        ),
        migrations.AddField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='seeker',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='seeker',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='seeker',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
