# Generated by Django 3.0.5 on 2020-04-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200413_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='expertiseFields',
            field=models.TextField(default='non'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='seekingFields',
            field=models.TextField(default='non'),
        ),
    ]
