language: python
python:
- 3.8
script:
- python manage.py test
deploy:
  provider: heroku:git
  app: advisor-api
  on:
    branch: feature/travis
  edge: true
  api_key:
    secure: W9tVpjamJOP/Exad9VbQZzz8PnQtqEefENz59LWYFNCGu/OT3wUv1cbxRVr6gKUul1p5IxMijBwI/SB6s16tzz+fAGqzaN4qvqW59R7QWJT7CqPCNHCXcSJx98UOAf9ghyXbX02sK9BiidW4hMB1LAdKRZ0x51xZDXRe0oPY8lcFt1jwurNwLSo9aK083ZKmJXvREBZRsMzSKfG+NAWcm89T8rLXMlWuii09MM/vzL99sfH5IIAjvjI5QVHcDpTAU/RxAj151niskCLIUOS/0h+GrIPNmmKUDvd84Tsp6/NlnM3Cn5e7zYfwiG1dPvvhe2m2zdUa7wojgl+ybvnui9yKB4MAyMWD/5qnp8AuXtcmCzBRTQDhAQegOK2weKK53Hjb/I1fLs7rDB8BQ7ltgJXFTxHK49AOPYYHY45YzcBsFQTF9PQiPynl7yQvVsitjYLPgufOj5GssjeQhESbZBEsx866oFdMQgu7z8ei6sCLYNu6ZeIoarRlLPGFq3d5c8LJM84ZQVR5aqBAed+oF7IXdXBKXZ0sMO/FMQc8PxslHVb16+UYTh0z75WBQLwOqPaH1HBSqVhY3OXA3VsojUczfbV5JCVXoTACBlGZyDe/NPQlleBBHddLBeqTSK5qz60ybrPYLmS1vC2cB8IKTJYA+/eG7F4dyql+2GMPDEc=
