# Generated by Django 3.0.6 on 2020-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='okta_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
