# Generated by Django 3.0.6 on 2020-05-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentoringtags_seekingtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('0', 'male'), ('1', 'female')], default='female', max_length=55, verbose_name='gender')),
                ('personal_des', models.TextField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, verbose_name='year-month-day')),
                ('is_available', models.BooleanField(default=False)),
                ('mentoring_tags', models.ManyToManyField(to='core.SeekingTags')),
                ('seeking_tags', models.ManyToManyField(to='core.MentoringTags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
