# Generated by Django 3.0.5 on 2020-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mentoring_tags',
            field=models.ManyToManyField(to='core.MentoringTags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seeking_tags',
            field=models.ManyToManyField(to='core.SeekingTags'),
        ),
    ]
