# Generated by Django 3.0.5 on 2020-05-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200511_1419'),
        ('core', '0005_auto_20200511_2042'),
    ]

    operations = [
    ]
