# Generated by Django 3.0.5 on 2020-04-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advisor',
        ),
    ]
