# Generated by Django 3.0.5 on 2020-04-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
