name: Django CI

on:
  push:
    branches:
      - master
      - feature/*
    paths:
      - backend/*
  pull_request:
    branches:
      - master
    paths:
      - backend/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py test
      - name: Deploy API to Heroku
        if: github.rer == 'master'
        uses: AkhileshNS/heroku-deploy@v3.0.2
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Email that you use with heroku
          heroku_email: advisor.ireland.web@gmail.com
          # The appname to use for deploying/updating
          heroku_app_name: advisor-api
          # An optional buildpack to use when creating the heroku application
          buildpack: https://github.com/heroku/heroku-buildpack-multi-procfile
          # The branch that you would like to deploy to Heroku
          branch: HEAD       
          # Set if your app is located in a subdirectory.
          appdir: backend
